spring:
    redis:
      cluster:
        nodes: 10.10.53.13:20020,10.10.53.13:20021,10.10.53.13:20030,10.10.53.13:20031,10.10.53.13:20010,10.10.53.13:20011
      lettuce:
          pool:
              max-active: 7
              max-idle: 7
              max-wait: -1ms
              min-idle: 2
          shutdown-timeout: 200ms
      password:
      port: 17103
server:
  port: 18080