httpclient:
    connectTimeout: 500
    requestTimeout: 500
    socketTimeout: 500
    defaultMaxPerRoute: 20
    maxTotalConnections: 200
    defaultKeepAliveTimeMillis: 20000
    closeIdleConnectionWaitTimeSecs: 30